"""Clean-process import checks for public modules."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

SOURCE_DIR = Path(__file__).resolve().parents[1] / "src"
PUBLIC_MODULES = [
    "langharness",
    "langharness.__main__",
    "langharness.api_guard",
    "langharness.bootstrap",
    "langharness_scope",
    "langharness_scope.contracts",
    "langharness_scope.errors",
    "langharness_scope.model",
    "langharness_scope.sqlite",
    "langharness_scope.tree",
    "langharness_core",
    "langharness_core.contracts",
    "langharness_core.plugin",
    "langharness_core.common.dependencies",
    "langharness_core.common.ids",
    "langharness_plugin",
    "langharness_plugin.config_store",
    "langharness_plugin.coordinator",
    "langharness_plugin.contracts",
    "langharness_plugin.discovery",
    "langharness_plugin.package",
    "langharness_plugin.registry",
    "langharness_plugin.plugin_manager",
    "langharness_plugin.scope_const",
    "langharness_plugin.scope_policy",
    "langharness_plugin.state_store",
    "langharness_plugin.validation",
    "langharness_core.plugins",
    "langharness_core.plugins.agents",
    "langharness_core.plugins.agents.directory",
    "langharness_core.plugins.agents.registry",
    "langharness_core.plugins.sessions",
    "langharness_core.plugins.sessions.sqlite",
    "langharness_core.plugins.loop",
    "langharness_core.plugins.loop.agent_loop",
    "langharness_core.plugins.llm.llm",
    "langharness_core.plugins.tools.tools",
    "langharness_core.plugins.tools.export_adapter",
    "langharness_core.plugins.tools.workspace",
    "langharness_core.plugins.middleware.template_middleware",
    "langharness_core.plugins.system_prompt.template_system_prompt",
    "langharness_core.plugins.response_format.template_response_format",
    "langharness_core.plugins.state_schema.template_state_schema",
    "langharness_core.plugins.context_schema.template_context_schema",
    "langharness_core.plugins.checkpointer.template_checkpointer",
    "langharness_core.plugins.checkpointer.sqlite",
    "langharness_core.plugins.store.template_store",
    "langharness_core.plugins.interrupt_before.template_interrupt_before",
    "langharness_core.plugins.interrupt_after.template_interrupt_after",
    "langharness_core.plugins.debug.template_debug",
    "langharness_core.plugins.name.template_name",
    "langharness_core.plugins.cache.template_cache",
    "langharness_core.plugins.transformers.template_transformers",
    "langharness_config.plugin",
    "langharness_logging.plugin",
    "langharness_logging.plugins.log",
    "langharness_api",
    "langharness_api.plugin",
    "langharness_api.sdk",
    "langharness_api.common.server",
    "langharness_api.common.errors",
    "langharness_api.plugins",
    "langharness_api.plugins.routes.agents",
    "langharness_api.plugins.routes.plugins",
    "langharness_api.plugins.routes.scopes",
    "langharness_api.plugins.routes.sessions",
    "langharness_api.plugins.server.app",
    "langharness_api.plugins.server.runtime",
    "langharness_api.plugins.sdk.http",
    "langharness_cli",
    "langharness_cli.plugin",
    "langharness_cli.common.cli",
    "langharness_cli.common.i18n",
    "langharness_cli.common.interactive",
    "langharness_cli.common.runner",
    "langharness_cli.common.session",
    "langharness_cli.plugins",
    "langharness_cli.plugins.commands.health",
    "langharness_cli.plugins.commands.plugins",
    "langharness_cli.plugins.commands.scope",
    "langharness_cli.plugins.commands.session",
    "langharness_cli.plugins.server",
    "langharness_core.plugins.agents.server",
]


def test_public_modules_import_in_clean_process() -> None:
    env = {**os.environ, "PYTHONPATH": str(SOURCE_DIR)}
    for module in PUBLIC_MODULES:
        result = subprocess.run(
            [sys.executable, "-c", f"import {module}"],
            env=env,
            check=False,
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"{module} failed:\n{result.stderr}"
